name: Publish VS Code Extension

on:
  push:
    # Run only when tags are pushed
    tags:
      - 'v*'
  release:
    types: [published]

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then echo "Found package-lock.json, running npm ci" && npm ci; else echo "No package-lock.json, running npm install" && npm install; fi

      - name: Compile extension
        run: |
          npm run compile

      - name: Install vsce
        run: |
          npm install -g @vscode/vsce

      - name: Package extension
        run: |
          npx @vscode/vsce package

      - name: Upload VSIX artifact (tags)
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: '*.vsix'

      - name: Publish to Marketplace (releases)
        if: github.event_name == 'release'
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: |
          npx @vscode/vsce publish --pat $VSCE_PAT
